name: Android CI Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Restore Gradle Cache
      uses: actions/cache@v1
      with: 
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os}}-gradle-
          
    - name: Gradle build
      run: ./gradlew :app:assemble
    
    - name: Gradle run unit tests
      run: ./gradlew :app:testDebugUnitTest
